### ISSUE TITLE
Backport CMFEditions modifier to 1.0.x branch

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.app.tiles#18]
We're using `plone.app.tiles = 1.0.2` in collective.cover; we need this fix in 1.x branch in order to get this issue closed: https://github.com/collective/collective.cover/issues/532

See #15 for more details.

A new release will be needed.

**Comment by datakurre** [comment]
https://github.com/plone/plone.app.tiles/pull/17

**Comment by hvelarde** [comment]
thanks!
