### ISSUE TITLE
Backport CMFEditions modifier to 2.x branch

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.app.tiles#19]
To keep updating collective.cover's dependencies we need to use branch 2.x of this package.

We need to backport this fix also here.

See #15 for more details.

**Comment by datakurre** [comment]
@rodfersou FYI. Commits from 1.x backport pull could be trivially cherry-pickable for 2.x https://github.com/plone/plone.app.tiles/pull/17/commits

**Comment by hvelarde** [comment]
@datakurre there's no 2.x branch

**Comment by petschki** [comment]
As I've seen you're depending on `p.a.tiles = 3.0.3` in https://github.com/collective/collective.cover/blob/master/versions-4.3.x.cfg I'll close this.
