### ISSUE TITLE
Unable to delete tiles with @@delete-tile

### ISSUE THREAD

**Issue by cekk** [plone/plone.app.tiles#24]
With Plone 5.1b2 + plone.autoform 1.7.2 i have a strange issue.
If i use the views to manage tiles (@@add-tile, @@edit-tile, @@delete-tile), i can add and edit the tile, but i can't delete it.

For example, calling http://localhost:8080/Plone/front-page/@@delete-tile/my.tile.type/ff4284f273f64a9ebff3e2e29f25089b
I have the following traceback

    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module plone.z3cform.layout, line 63, in __call__
      Module plone.z3cform.layout, line 47, in update
      Module plone.app.tiles.browser.base, line 72, in update
      Module plone.z3cform.fieldsets.extensible, line 64, in update
      Module plone.autoform.form, line 34, in updateFields
      Module plone.autoform.base, line 133, in updateFieldsFromSchemata
      Module plone.autoform.base, line 160, in _cleanup_rules
    TypeError: 'NoneType' object has no attribute '__getitem__'

The problem is in plone.autoform in _cleanup_rules because the context doesn't have rules (rules is None).
I don't know if this could be an error in p.a.tiles or plone.autorform.
In a Plone 5.0.x with plone.autoform 1.6.2 i don't have this problem

**Comment by datakurre** [comment]
https://github.com/plone/plone.autoform/issues/20

**Comment by cekk** [comment]
ok, so i could use 1.6.x until it'll be resolved. Thanks

Should we fix version also here to avoid problems?

**Comment by datakurre** [comment]
Yes, I believe that 1.7.x is mostly about cleanup and I have not been missing anything with 1.6.x.

I'm still hoping that the regression in 1.7.x would be fixed before Plone 5.1 final.

**Comment by keul** [comment]
Seem fixed at revision https://github.com/plone/plone.autoform/commit/9c493dee6b4404d12dcca5df187e6989449ef0e1

**Comment by petschki** [comment]
fix confirmed
