### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by petschki** [plone/plone.app.tiles#27]
see #26 and #25

**Comment by cekk** [comment]
@petschki python3 is in a working state or still in progress?
Because i'm trying to add some tiles with add form and it's not working.

I get a not found error when [handleAdd](https://github.com/plone/plone.app.tiles/blob/python3/plone/app/tiles/browser/add.py#L61) tries to traverse to the new created tile.

**Comment by petschki** [comment]
@cekk sorry ... far from working ... maybe I have a bit time for this next week on the AlpineCitySprint ...

**Comment by petschki** [comment]
@cekk thank you. any help much appreciated! I'll keep you informed.

**Comment by petschki** [comment]
@cekk I've made some progress on the [mosaic issues](https://github.com/plone/plone.app.mosaic/issues/432) ... all in all it looks good for Plone 5.2/py2.7 but you have to build it with the coredev branch 5.2. It would be great if you have time to try things out ... just `git clone -b 5.2 https://github.com/plone/buildout.coredev plone5.2` and add a `local.cfg` which looks something like this:

```
[buildout]
auto-checkout +=
    plone.app.mosaic
#   mosaic additional
    plone.jsonserializer
    plone.tiles
    plone.app.tiles
    plone.app.blocks
    plone.app.drafts
    plone.app.standardtiles
# ecosystem
    collective.themefragments

custom-eggs +=
    plone.app.mosaic

test-eggs +=
    plone.app.blocks
    plone.app.mosaic

[sources]
plone.app.mosaic = git ${remotes:plone}/plone.app.mosaic.git pushurl=${remotes:plone_push}/plone.app.mosaic branch=plone-5.2.x-py2.7
plone.app.blocks = git ${remotes:plone}/plone.app.blocks.git pushurl=${remotes:plone_push}/plone.app.blocks branch=python3
plone.app.drafts = git ${remotes:plone}/plone.app.drafts.git pushurl=${remotes:plone_push}/plone.app.drafts branch=py3plone52
plone.app.standardtiles = git ${remotes:plone}/plone.app.standardtiles.git pushurl=${remotes:plone_push}/plone.app.standardtiles.git
plone.app.tiles = git ${remotes:plone}/plone.app.tiles.git pushurl=${remotes:plone_push}/plone.app.tiles.git branch=python3
plone.tiles = git ${remotes:plone}/plone.tiles.git pushurl=${remotes:plone_push}/plone.tiles.git branch=master
plone.jsonserializer = git ${remotes:plone}/plone.jsonserializer.git pushurl=${remotes:plone_push}/plone.jsonserializer branch=python3

collective.themefragments = git ${remotes:collective}/collective.themefragments.git egg=false pushurl=${remotes:collective_push}/collective.themefragments.git
```

Right now I'm finishing 'plone.app.blocks`python3 porting and after that I'll look at 'plone.app.mosaic' ... feel free to contact me on the IRC channels if you need help (plone or sprint ... but only on gitter.im/plone) ...

NOTE on python3 porting:

I really like the https://github.com/jensens/coredev52multipy buildout from jensens where you have the sources in a shared `/src` folder which is used for py2 and py3 ... this makes it easy to test your changes in py2.7 and py3 at once.

**Comment by cekk** [comment]
I don't use mosaic, but i tried your changes here, and now i can add tiles correctly with my manager.
👍
