### ISSUE TITLE
Why test on Plone 5.2 with Python 3.9?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.tiles#45]
With tox and GitHub Actions we test Plone 5.2 on various Python versions including Python 3.9.
This is not a supported combination and I don't recommend it. I know changes in Zope 5 were needed to support Python 3.9.

@petschki Maybe you added this combination by accident?
Can I remove it?

I noticed because on my Mac with Python 3.9 I cannot compile Pillow 6.2.2 because zlib cannot be found. Possibly fixable with some more compiler flags.

**Comment by petschki** [comment]
Yes please remove it. Doesn’t make sense.

**Comment by mauritsvanrees** [comment]
Done directly on master.
